/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-variant": "#262626",
        "on-error": "#490013",
        "secondary-dim": "#00ecec",
        "tertiary-dim": "#ff51fa",
        "surface-container": "#1a1919",
        "on-tertiary-fixed": "#320032",
        "on-primary-fixed": "#000000",
        "on-tertiary": "#400040",
        "surface-container-highest": "#262626",
        "on-primary": "#47007b",
        "on-primary-fixed-variant": "#440076",
        "surface-container-high": "#201f1f",
        "on-secondary-fixed": "#004747",
        "primary-dim": "#bf83f8",
        "background": "#0e0e0e",
        "on-error-container": "#ffb2b9",
        "surface-container-lowest": "#000000",
        "secondary-container": "#006a6a",
        "surface-container-low": "#131313",
        "on-secondary-container": "#d9fffe",
        "surface-bright": "#2c2c2c",
        "primary": "#cc97ff",
        "error-container": "#a70138",
        "inverse-primary": "#7c42b3",
        "outline": "#777575",
        "surface-tint": "#cc97ff",
        "on-surface-variant": "#adaaaa",
        "on-secondary-fixed-variant": "#006666",
        "on-background": "#ffffff",
        "secondary-fixed-dim": "#00ecec",
        "tertiary-fixed-dim": "#ff61f8",
        "on-secondary": "#005c5c",
        "on-primary-container": "#360061",
        "on-surface": "#ffffff",
        "tertiary-fixed": "#ff81f5",
        "secondary": "#00fbfb",
        "primary-container": "#c285fb",
        "inverse-on-surface": "#565554",
        "surface-dim": "#0e0e0e",
        "on-tertiary-fixed-variant": "#6a006a",
        "outline-variant": "#494847",
        "on-tertiary-container": "#230023",
        "error-dim": "#d73357",
        "primary-fixed": "#c285fb",
        "secondary-fixed": "#00fbfb",
        "inverse-surface": "#fcf8f8",
        "tertiary": "#ff51fa",
        "tertiary-container": "#fe00fe",
        "primary-fixed-dim": "#b478ed",
        "error": "#ff6e84",
        "surface": "#0e0e0e",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Space Grotesk", "sans-serif"],
        antiqua: ["Modern Antiqua", "serif"],
      },
    },
  },
  plugins: [],
};
